package thesis;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.datatransfer.DataFlavor;
import java.awt.datatransfer.Transferable;
import java.awt.dnd.DnDConstants;
import java.awt.dnd.DropTarget;
import java.awt.dnd.DropTargetDropEvent;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.TextStyle;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author gouvo
 */
public class SceduleManager extends JFrame {
    
    private JTable table;
    private ExcelManager excelManager;

    public SceduleManager() {
    }
    
    public SceduleManager(ExcelManager excelManager) {
        initComponents();
        
        this.excelManager = excelManager;
        
            table.setDropTarget(new DropTarget() {
            @Override
            public synchronized void drop(DropTargetDropEvent evt) {
                try {
                    Transferable transferable = evt.getTransferable();
                    if (transferable.isDataFlavorSupported(DataFlavor.stringFlavor)) {
                        evt.acceptDrop(DnDConstants.ACTION_MOVE);
                        String courseName = (String) transferable.getTransferData(DataFlavor.stringFlavor);

                        // Handle the dropped courseName on the table
                        // You can get the table coordinates using evt.getLocation()

                        evt.dropComplete(true);
                    } else {
                        evt.rejectDrop();
                    }
                } catch (Exception e) {
                    e.printStackTrace();
                    evt.rejectDrop();
                }
            }
        });
        
        modelPanel.setLayout(new BorderLayout());
        modelPanel.add(populateTable(), BorderLayout.CENTER);
        
        coursesPanel.setLayout(new GridLayout(5,5));
        populateCourses();
        
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        this.setSize(800, 600);
        
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }

    public void populateCourses() {
        List<Course> courses = new ArrayList<>(excelManager.getCourses()); // Replace this with your actual list of courses
        for (Course course : courses) {
            // Create a custom component (e.g., JPanel or JButton) for each course
            JButton courseButton = new JButton(course.getCourseName());
            courseButton.setPreferredSize(new Dimension(100, 50)); // Set preferred size as needed
            courseButton.setText(course.getCourseName());
            courseButton.setBackground(Color.red);
            courseButton.setTransferHandler(new ButtonTransferHandler(course.getCourseName()));

            coursesPanel.add(courseButton);
        }
    }
    


    
    public JScrollPane populateTable(){
        List<String> timeslots = excelManager.getTimeslots();
        List<String> dates = new ArrayList<>(excelManager.getDates());
        DateTimeFormatter dateFormatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");

        int excelRows = dates.size();
        int excelCols = timeslots.size();
        
        // Create a DefaultTableModel with custom data
        DefaultTableModel model = new DefaultTableModel(excelRows + 1, excelCols + 1);
        
        for (int z = 0; z<timeslots.size(); z++){
            System.out.println(timeslots.get(z));
        }
        for (int i = 0; i < excelRows; i++) {
            LocalDate date = LocalDate.parse(dates.get(i), dateFormatter);
            String greekDayName = date.getDayOfWeek().getDisplayName(TextStyle.FULL, Locale.forLanguageTag("el-GR"));
            model.setValueAt(dates.get(i) + " " + greekDayName, i + 1, 0);
        }
        
        for (int j = 0; j < excelCols; j++){
            model.setValueAt(timeslots.get(j), 0, j + 1);
        }
        
        table = new JTable(model);

        JScrollPane scrollPane = new JScrollPane(table);
        scrollPane.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_ALWAYS);
        return scrollPane;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        modelPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        coursesPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(960, 800));
        getContentPane().setLayout(null);

        jScrollPane1.setPreferredSize(new java.awt.Dimension(800, 500));

        modelPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        modelPanel.setPreferredSize(new java.awt.Dimension(900, 500));

        javax.swing.GroupLayout modelPanelLayout = new javax.swing.GroupLayout(modelPanel);
        modelPanel.setLayout(modelPanelLayout);
        modelPanelLayout.setHorizontalGroup(
            modelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 922, Short.MAX_VALUE)
        );
        modelPanelLayout.setVerticalGroup(
            modelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 494, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(modelPanel);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 10, 940, 290);

        coursesPanel.setLayout(null);
        jScrollPane2.setViewportView(coursesPanel);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(20, 340, 930, 210);

        jLabel1.setText("Μαθήματα:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 310, 90, 16);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SceduleManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SceduleManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SceduleManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SceduleManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SceduleManager().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel coursesPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel modelPanel;
    // End of variables declaration//GEN-END:variables
}
